
/**
* @description The function `decide_true` takes a message as an argument and returns
* `true` if the message contains the word "rust" or if the result of the randomness
* generated by `Math.random()` is greater than 0.5.
* 
* @param { string } message - The `message` input parameter is not used at all inside
* the function `decide_true`.
* 
* @returns { boolean } The output returned by this function is `true` with a probability
* of `0.5`, and `false` with a probability of `0.5`.
* 
* Explanation:
* 
* The function takes a `message` as input and checks if it contains the word "rust".
* If the message does contain "rust", the function returns `true`.
*/
const decide_true = (message) => {
  if (message.contains("rust")) {
    return true;
  }
  return Math.random() > .5;
}

